# .github/workflows/ci.yml
name: Backend CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
       
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django Tests
        run: |
          python manage.py test 

  build:
    needs: test
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true 
          tags: |
            zhaoxinmei/tasksphere-backend:v0.0.${{ github.run_number }}
            zhaoxinmei/tasksphere-backend:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << "EOF"
            set -e
            cd /home/ubuntu/TaskSphere-Backend
            
            # 1. 重新构建镜像
            sudo docker build -t django_app:latest .
            
            # 2. 停止并移除旧容器
            sudo docker rm -f django_app || true
            
            # 3. 启动新容器
            # 我们通过 --env-file 指向宿主机上的软链接或实际文件
            sudo docker run -d \
              --name django_app \
              --network app_net \
              --env-file /home/ubuntu/soft806.env \
              -p 8000:8000 \
              django_app:latest
            
            # 4. 稍微等一下数据库响应
            sleep 5
            
            # 5. 执行迁移
            sudo docker exec django_app python manage.py migrate
          EOF
